language: csharp
dotnet: 3.1
solution: TestDeploy.sln
mono: none

sudo: required
services:
  - docker

before_install:
  - docker build -f TestDeploy/Dockerfile -t testdeploy .

scripts:
  - dotnet restore

deploy:
  on:
    branch: master
