sudo: required
services:
  - docker

before_install:
  - docker build -f TestDeploy/Dockerfile -t testdeploy .

# scripts:
#   - docker run -e CI=true testdeploy dotnet test

deploy:
  on:
    branch: master
